language: node_js

node_js:
    - "8"
    - "10"
    - "12"
    - "14"
    
arch:
    - amd64
    - ppc64le

before_install:
     - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then    sudo apt-get install npm;   fi
